HEAP-38339 added no emotion css instance on component classname rule
heap/eslint-plugin-heap pull request #17
Opened 2023-01-05 15:46 UTC by xiyang786926

2023-01-06 16:50 UTC, xiyang786926 commented
<img width="1002" alt="Screen Shot 2023-01-06 at 11 49 31 AM" src="https://user-images.githubusercontent.com/78751744/211058702-4fe04944-bf3a-413d-b6f8-13a0586289c9.png">

2023-01-09 20:06 UTC, djsaun requested changes

2023-01-09 20:06 UTC, djsaun commented on src/rules/no-emotion-css-instance-classname.ts
> +const MESSAGE = 'emotion css instance should not use for classname, use emotion variable instead';
Can we please reword this to something like "Emotion's css property should not be used directly within a React component. Please move the css instance to a variable outside of the component's scope before using."

2023-01-19 18:45 UTC, greghuels approved these changes

2023-01-19 18:45 UTC, merged